"""add new guest field

Revision ID: 7a82162b4392
Revises: 004
Create Date: 2026-07-14 05:19:12.130897

"""
from alembic import op
import sqlalchemy as sa


revision = '7a82162b4392'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_list', sa.Column('pax', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest_list', 'pax')
    # ### end Alembic commands ###
